version: "3.1"
services:
  db:
    image: postgres:14.4-alpine
    container_name: poke-guesser-postgres
    restart: unless-stopped
    env_file:
      - ./docker.env
    networks:
      - default
    volumes:
      - ./docker-sql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
  poke-guesser-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    restart: unless-stopped
    image: poke-guesser-bot
    depends_on:
      - db
    env_file:
      - ./docker.env
    networks:
      - default
volumes:
  database:
networks:
  default:
