version: "3"
services:
  db:
    image: postgres:14.2
    container_name: poke-guesser-postgres
    restart: unless-stopped
    env_file:
      - docker.env
    networks:
      - default
    volumes:
      - ./docker-sql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  poke-guesser-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    command: node index.js
    restart: unless-stopped
    image: poke-guesser-bot
    depends_on:
      - db
    env_file:
      - docker.env
    networks:
      - default
volumes:
  db:
networks:
  default:
