version: "3.1"
services:
  db:
    image: postgres:15
    container_name: poke-guesser-postgres
    restart: "no"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
  poke-guesser-bot:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    restart: "no"
    image: poke-guesser-bot
    depends_on:
      - db
    networks:
      - default
networks:
  default:
