version: "3.1"
services:
  db:
    image: postgres:15
    container_name: poke-guesser-postgres
    restart: "no"
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    volumes:
      - ./docker-sql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
  poke-guesser-bot:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    restart: "no"
    image: poke-guesser-bot
    depends_on:
      - db
    networks:
      - default
volumes:
  database:
networks:
  default:
