name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
    steps:
    - name: Checkout Code
      id: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      if: steps.checkout.outcome == 'success'
      run: docker-compose build
    - name: Test the Docker image
      if: steps.checkout.outcome == 'success'
      run: docker-compose up --abort-on-container-exit
      timeout-minutes: 30
